// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type DanbooruApiResponse = DanbooruPost[];

interface DanbooruPost {
    id:                     number;
    created_at:             string;
    updated_at:             string;
    up_score:               number;
    down_score:             number;
    score:                  number;
    source:                 string | null;
    md5:                    string;
    rating:                 Rating;
    is_note_locked:         boolean;
    is_rating_locked:       boolean;
    is_status_locked:       boolean;
    is_pending:             boolean;
    is_flagged:             boolean;
    is_deleted:             boolean;
    uploader_id:            number;
    approver_id:            null;
    pool_string:            string;
    last_noted_at:          null | string;
    last_comment_bumped_at: null;
    fav_count:              number;
    tag_string:             string;
    tag_count:              number;
    tag_count_general:      number;
    tag_count_artist:       number;
    tag_count_character:    number;
    tag_count_copyright:    number;
    file_ext?:              string;
    file_size:              number;
    image_width:            number;
    image_height:           number;
    parent_id:              null;
    has_children:           boolean;
    is_banned:              boolean;
    pixiv_id:               number | null;
    last_commented_at:      null | string;
    has_active_children:    boolean;
    bit_flags:              number;
    tag_count_meta:         number;
    has_large:              boolean | null;
    has_visible_children:   boolean;
    tag_string_general:     string;
    tag_string_character:   string;
    tag_string_copyright:   string;
    tag_string_artist:      string;
    tag_string_meta:        string;
    file_url?:              string;
    large_file_url?:        string;
    preview_file_url?:      string;
}

enum Rating {
    Explicit = "e",
    Questionable = "q",
    Safe = "s",
}
