// Generated by ts-to-zod
import { Zod } from "@type/Zod";
import { z } from "zod";
import { ZAPISaucenaoAnime } from "./saucenao/Anime";
import { ZAPISaucenaoArtstation } from "./saucenao/Artstation";
import { ZAPISaucenaoEHentai } from "./saucenao/EHentai";
import { ZAPISaucenaoHAnime } from "./saucenao/HAnime";
import { ZAPISaucenaoHGame } from "./saucenao/HGame";
import { ZAPISaucenaoHMagazines } from "./saucenao/HMagazines";
import { ZAPISaucenaoMangadex } from "./saucenao/Mangadex";
import { ZAPISaucenaoMoebooru } from "./saucenao/Moebooru";
import { ZAPISaucenaoPawoo } from "./saucenao/Pawoo";
import { ZAPISaucenaoPixiv } from "./saucenao/Pixiv";
import { ZAPISaucenaoSeiga } from "./saucenao/Seiga";
import { ZAPISaucenaoTwitter } from "./saucenao/Twitter";

const indexSchema = z.object({
	status: z.number(),
	parent_id: z.number(),
	id: z.number(),
	results: z.number()
});

const resultHeaderSchema = z.object({
	similarity: z.string(),
	thumbnail: z.string(),
	index_id: z.number(),
	index_name: z.string(),
	dupes: z.number()
});

const headerSchema = z.object({
	user_id: z.string(),
	account_type: z.string(),
	short_limit: z.string(),
	long_limit: z.string(),
	long_remaining: z.number(),
	short_remaining: z.number(),
	status: z.number(),
	results_requested: z.number(),
	index: z.record(indexSchema),
	search_depth: z.string(),
	minimum_similarity: z.number(),
	query_image_display: z.string(),
	query_image: z.string(),
	results_returned: z.number(),
	message: z.string().optional()
});

const resultSchema = z.object({
	header: resultHeaderSchema,
	data: z.union([
		ZAPISaucenaoAnime.z,
		ZAPISaucenaoArtstation.z,
		ZAPISaucenaoEHentai.z,
		ZAPISaucenaoHAnime.z,
		ZAPISaucenaoHGame.z,
		ZAPISaucenaoHMagazines.z,
		ZAPISaucenaoMangadex.z,
		ZAPISaucenaoMoebooru.z,
		ZAPISaucenaoPawoo.z,
		ZAPISaucenaoPixiv.z,
		ZAPISaucenaoSeiga.z,
		ZAPISaucenaoTwitter.z
	])
});

export const ZAPISaucenao = new Zod(z.object({
	header: headerSchema,
	results: z.array(resultSchema)
}));

export type APISaucenao = z.infer<typeof ZAPISaucenao.z>;