// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface APIPixivUgoiraMeta {
    ugoira_metadata: UgoiraMetadata;
}

export interface UgoiraMetadata {
    zip_urls: ZipUrls;
    frames:   Frame[];
}

export interface Frame {
    file:  string;
    delay: number;
}

export interface ZipUrls {
    medium: string;
}